variables:
  # This is a place for you to define variables you can use
  # later in the script by referring to the variable like so:
  #   ${EXAMPLE_VARIABLE}
  EXAMPLE_VARIABLE: "Example"
  

image: maven:3.3.9-jdk-8

before_script:
  # Do anything you have to do before your stages below here.
  # For example, do you need to change permissions on a build folder
  # or modify a file to insert a variable from your CI config here?
  #- apt-get update -qy
  #- apt-get install -y openssh-client
  #- eval $(ssh-agent -s)
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  #- echo "$DEPLOY_SSH_KEY" | tr -d '\r'  | ssh-add -
  - ssh-add <(echo "$PRIVATE_KEY")
  #- echo "$DEPLOY_SSH_KEY" | ssh-add - > ~/.ssh/id_rsa

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/*


stages:
# These are the three states we want, building the app, testing it by
# executing unit tests and checking the results, and finally if this
  - build
  # You will need to define this stage somewhere below.
  - test
  # I will provide this example for you below.
  - deploy

buildStep:
  image: maven:latest
  stage: build
  tags:
    - ugrad
  artifacts:
    paths:
    - /target
  script:
    #mvn clean install
    mvn compile

testStep:
  image: maven:3-jdk-8
  stage: test
  tags:
    - ugrad
  artifacts:
    when: always
    reports:
      junit:
        - /target/surefire-reports/TEST-*.xml
  script:
    mvn clean test
    
deployTest:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - /target
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}"  "${DEPLOY_USER_PROD}@${DEPLOY_HOST}:${DEPLOY_DIR}/"
  environment:
    name: Production
  only:
    - master

deployProd:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - /target
  script:
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/"
  environment:
    name: Test
  only:
    - release
    
# deployStep:
#   stage: deploy
#   tags:
#     # I am tagging the ugrad runner, read this document to learn why:
#     # https://helpdesk.cs.dal.ca/gitlab
#     - ugrad
#   artifacts:
#     paths:
#       # Change this directory to the path that contains your built executable
#       - /target

#   script:
#     #- ssh-keygen -f ~/.ssh/id_rsa -p
#     #- chmod og-rwx ${DEPLOY_SSH_KEY}
#     #- chmod og-rwx ${PROD_DB_CONFIG}
#     #- chmod og-rwx ${SCHEMA}
#     # The following commands will zip your build folder, and transfer that
#     # zip file to the designated Timberlea account. You will need to change
#     # the <BUILDDIRECTORY> string to the actual directory where your build artifacts
#     # reside when your build commands are complete on the runner.
#     # Notice how these commands are using the variables you defined in your GitLab CI/CD
#     # settings in earlier steps. It will not work without those variables
#     - chmod og-rwx ${DEPLOY_SSH_KEY}
#     - zip -r ${CI_COMMIT_SHORT_SHA}.zip target
#     - scp -r -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir ${DEPLOY_DIR}"
#     - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"
    
#     #- scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"
#     - scp -r -o StrictHostKeyChecking=no /target/healthifyyou-0.0.1-SNAPSHOT.jar "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"
#     #- scp -r -o StrictHostKeyChecking=no ${PROD_DB_CONFIG} "${PROD_DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}/dbconfig.properties"
#     #- scp -r -o StrictHostKeyChecking=no ${SCHEMA} "${PROD_DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}/schema.json"
